# Generated by Django 5.2 on 2025-04-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0003_articletag_artcilepage_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtcilePage',
            new_name='ArticlePage',
        ),
    ]
