# Generated by Django 5.2 on 2025-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0004_rename_artcilepage_articlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='views',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
